// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Heartbeat struct {
	ID         string `json:"id"`
	StatusCode int32  `json:"statusCode"`
	LatencyMs  int32  `json:"latencyMs"`
	IsUp       bool   `json:"isUp"`
	CreatedAt  string `json:"createdAt"`
}

type Monitor struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	URL       string        `json:"url"`
	Method    string        `json:"method"`
	Timeout   int32         `json:"timeout"`
	Frequency int32         `json:"frequency"`
	IsActive  bool          `json:"isActive"`
	IsUp      bool          `json:"isUp"`
	CreatedAt string        `json:"createdAt"`
	Stats24h  *MonitorStats `json:"stats24h"`
}

type MonitorStats struct {
	UptimePercentage float64      `json:"uptimePercentage"`
	AverageLatencyMs float64      `json:"averageLatencyMs"`
	History          []*Heartbeat `json:"history"`
}

type Query struct {
}
