package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"
	"time"
	"uptime-monitor-backend/internal/auth"
	"uptime-monitor-backend/internal/graph/model"
)

// GetMonitorStats is the resolver for the getMonitorStats field.
func (r *queryResolver) GetMonitorStats(ctx context.Context, monitorID string) (*model.Monitor, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("Not authorized")
	}

	monitor, err := r.MonitorService.FindByUserAndID(userID, monitorID)
	if err != nil {
		return nil, fmt.Errorf("find monitor by id: %w", err)
	}

	heartbeats, err := r.HearbeatService.List24hBymonitor_id(monitorID)
	if err != nil {
		return nil, fmt.Errorf("list heartbeats by monitor id: %w", err)
	}

	uptimePercentage := calculateUptimePercentage(heartbeats)
	averageLatency := calculateAverageLatency(heartbeats)

	return &model.Monitor{
		ID:        monitor.ID,
		Name:      monitor.Name,
		URL:       monitor.URL,
		Method:    monitor.Method,
		Timeout:   int32(monitor.Timeout),
		Frequency: int32(monitor.Frequency),
		IsActive:  monitor.IsActive,
		IsUp:      monitor.IsUp,
		CreatedAt: monitor.CreatedAt.Format(time.DateTime),
		Stats24h: &model.MonitorStats{
			UptimePercentage: uptimePercentage,
			AverageLatencyMs: averageLatency,
			History:          toModelHeartbeats(heartbeats),
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
