package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"
	"time"
	"uptime-monitor-backend/internal/auth"
	"uptime-monitor-backend/internal/graph/model"
	"uptime-monitor-backend/internal/hearbeat"
)

// GetMonitorStats is the resolver for the getMonitorStats field.
func (r *queryResolver) GetMonitorStats(ctx context.Context, monitorID string) (*model.Monitor, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("Not authorized")
	}

	monitor, err := r.MonitorService.FindByID(userID, monitorID)
	if err != nil {
		return nil, fmt.Errorf("find monitor by id: %w", err)
	}

	heartbeats, err := r.HearbeatService.List24hByMonitorID(monitorID)
	if err != nil {
		return nil, fmt.Errorf("list heartbeats by monitor id: %w", err)
	}

	uptimePercentage := calculateUptimePercentage(heartbeats)
	averageLatency := calculateAverageLatency(heartbeats)

	return &model.Monitor{
		ID:   monitor.ID,
		Name: monitor.Name,
		Stats24h: &model.MonitorStats{
			UptimePercentage: uptimePercentage,
			AverageLatencyMs: averageLatency,
			History:          toModelHeartbeats(heartbeats),
		},
	}, nil
}

func calculateUptimePercentage(heartbeats []hearbeat.Heartbeat) float64 {
	if len(heartbeats) == 0 {
		return 0
	}

	uptime := 0
	for _, heartbeat := range heartbeats {
		if heartbeat.IsUp {
			uptime++
		}
	}
	return (float64(uptime) / float64(len(heartbeats))) * 100
}

func calculateAverageLatency(heartbeats []hearbeat.Heartbeat) float64 {
	if len(heartbeats) == 0 {
		return 0
	}

	latency := 0
	for _, heartbeat := range heartbeats {
		latency += heartbeat.LatencyMs
	}
	return float64(latency) / float64(len(heartbeats))
}

func toModelHeartbeats(heartbeats []hearbeat.Heartbeat) []*model.Heartbeat {
	modelHeartbeats := make([]*model.Heartbeat, 0, len(heartbeats))
	for _, heartbeat := range heartbeats {
		modelHeartbeats = append(modelHeartbeats, &model.Heartbeat{
			ID:         heartbeat.ID,
			StatusCode: int32(heartbeat.StatusCode),
			LatencyMs:  int32(heartbeat.LatencyMs),
			IsUp:       heartbeat.IsUp,
			CreatedAt:  heartbeat.CreatedAt.Format(time.RFC3339),
		})
	}
	return modelHeartbeats
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
